### PR TITLE
Make private docker build

### PR DESCRIPTION
**Pull request by jkeslin-godaddy**
This forked action uses a docker image that is not controlled by us. This PR adds a Actions workflow to build the docker container ourselves and push to our own Packages registry.

### CODE REVIEW

**Comment by jkeslin-godaddy** [comment]
Just for context -- we happily use this Action on various internal repos, but due to security requirements, we cannot depend on the public repo for it. So this is just a fork of the repo that we can audit and manage.

**Review by mxhenry-godaddy — CHANGES_REQUESTED** [review]
Can we add the CODEOWNERS file back please?

**Comment by jkeslin-godaddy** [comment]
> Can we add the CODEOWNERS file back please?

@mxhenry-godaddy The CODEOWNERS file referenced the original owner for the Action -- do we want PRs into this repo to trigger review requests from them?

**Comment by mxhenry-godaddy** [comment]
> Can we add the CODEOWNERS file back please?

riggaroo  is a GD account

**Review by mxhenry-godaddy — APPROVED** [review]

**Review by riggaroo — APPROVED** [review]

**Pull request merged**
